### ISSUE TITLE
Merge `kubeRL` scheduler extender

### ISSUE THREAD

**Issue by wangchen615** [IBM/kube-safe-scheduler#19]
`kubeRL` is a software framework implementing a reward biased scheduler extender in Kubernetes. `kubeRL` adopts the idea from reinforcement learning to adaptively learn the failures or performance issues of containers and model their runtime performance on nodes as rewards. `kubeRL` then adaptively prevents scheduling pods on nodes that give low rewards.

**Comment by atantawi** [comment]
Merged
